In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("IPL IMB381IPL2013.csv")

In [3]:
df.head()

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0.00,0,307,15,20.47,8.90,13.93,2009,50000,50000
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0.00,0,29,0,0.00,14.50,0.00,2008,50000,50000
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,121.01,5,1059,29,36.52,8.81,24.90,2008,200000,350000
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,76.32,0,1125,49,22.96,6.23,22.14,2011,100000,850000
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,120.71,28,0,0,0.00,0.00,0.00,2011,100000,800000

In [4]:
df['PLAYER NAME'].head(10)

0      Abdulla, YA
1     Abdur Razzak
2      Agarkar, AB
3        Ashwin, R
4     Badrinath, S
5       Bailey, GJ
6        Balaji, L
7    Bollinger, DE
8         Botha, J
9      Boucher, MV
Name: PLAYER NAME, dtype: object

In [5]:
df.loc[df['PLAYER NAME']=='Kohli, V']
df[['PLAYER NAME','SOLD PRICE']].sort_values('SOLD PRICE',ascending=False).head(20)


df.groupby('COUNTRY')



## HIGHEST SOLD PRICE PLAYERS

df.loc[df['SOLD PRICE']==max(df['SOLD PRICE'])]



# df.head(20)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
50,51,"Kohli, V",1,IND,RCB,Batsman,491,0,3590,86.31,...,119.29,49,345,4,86.25,8.84,58.50,2011,150000,1800000
93,94,"Sehwag, V",2,IND,DD,Batsman,8178,40,8090,104.68,...,167.32,79,226,6,37.67,10.56,21.67,2011,400000,1800000
111,112,"Tendulkar, SR",3,IND,MI,Batsman,15470,45,18426,86.23,...,119.22,24,58,0,0.00,9.67,0.00,2011,400000,1800000
127,128,Yuvraj Singh,2,IND,KXIP+,Batsman,1775,9,8051,87.58,...,131.88,67,569,23,24.74,7.02,21.13,2011,400000,1800000

In [6]:
df.loc[2:5]


df.iloc[1:4,2:7]


#CSK team
df.loc[df['TEAM']=='CSK'].head(20)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,76.32,0,1125,49,22.96,6.23,22.14,2011,100000,850000
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,120.71,28,0,0,0.00,0.00,0.00,2011,100000,800000
5,6,"Bailey, GJ",2,AUS,CSK,Batsman,0,0,172,72.26,...,95.45,0,0,0,0.00,0.00,0.00,2009,50000,50000
7,8,"Bollinger, DE",2,AUS,CSK,Bowler,54,50,50,92.59,...,165.88,1,693,37,18.73,7.22,15.57,2011,200000,700000
15,16,"Dhoni, MS",2,IND,CSK,W. Keeper,3509,0,6773,88.19,...,136.45,64,0,0,0.00,0.00,0.00,2008,400000,1500000
22,23,"Fleming, SP",3,NZ,CSK,Batsman,7172,0,8037,71.49,...,118.78,3,0,0,0.00,0.00,0.00,2008,350000,350000
23,24,"Flintoff, A",2,ENG,CSK,Allrounder,3845,226,3394,88.82,...,116.98,2,105,2,52.50,9.55,33.00,2009,950000,1550000
32,33,"Hayden, ML",3,AUS,CSK,Batsman,8625,0,6133,78.96,...,137.52,44,0,0,0.00,0.00,0.00,2008,225000,375000
38,39,"Hussey, MEK",3,AUS,CSK,Batsman,5708,7,5262,86.97,...,120.65,25,0,0,0.00,0.00,0.00,2008,250000,250000
67,68,"Morkel, JA",2,SA,CSK,Allrounder,58,1,782,100.25,...,146.25,45,1899,69,27.52,8.25,20.01,2008,225000,675000
74,75,"Ntini, M",2,SA,CSK,Bowler,699,390,199,66.77,...,61.11,0,242,7,34.57,6.91,30.00,2008,200000,200000
88,89,"Raina, SK",1,IND,CSK,Batsman,710,13,3525,92.71,...,139.39,97,678,20,33.90,7.05,28.90,2008,125000,650000
96,97,"Sharma, J",2,IND,CSK,Allrounder,0,0,35,116.66,...,120.00,2,419,12,34.92,9.88,21.33,2008,100000,225000
114,115,"Tyagi, S",1,IND,CSK,Bowler,0,0,1,50.00,...,0.75,0,295,6,49.17,8.55,34.83,2011,50000,240000

In [7]:
#total runs scored in ipl 2013
sum(df['RUNS-S'])


# maximum runs by each player in each team

df[['PLAYER NAME','TEAM','RUNS-S']].groupby('TEAM').max()



# maximum runs by ech country player

df.loc[df.groupby('TEAM')['RUNS-S'].idxmax(),['PLAYER NAME','TEAM','RUNS-S']]

# maximum exp
#df[['CAPTAINCY EXP','TEAM']].groupby('TEAM').max()


df.loc[df.groupby('PLAYING ROLE')['RUNS-S'].idxmax(),['PLAYER NAME','COUNTRY','TEAM','RUNS-S','PLAYING ROLE']]

        PLAYER NAME COUNTRY TEAM  RUNS-S PLAYING ROLE
44       Kallis, JH      SA  RCB    1965   Allrounder
88        Raina, SK     IND  CSK    2254      Batsman
30  Harbhajan Singh     IND   MI     430       Bowler
15        Dhoni, MS     IND  CSK    1782    W. Keeper

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.NO.         130 non-null    int64
 1   PLAYER NAME    130 non-null    object
 2   AGE            130 non-null    int64
 3   COUNTRY        130 non-null    object
 4   TEAM           130 non-null    object
 5   PLAYING ROLE   130 non-null    object
 6   T-RUNS         130 non-null    int64
 7   T-WKTS         130 non-null    int64
 8   ODI-RUNS-S     130 non-null    int64
 9   ODI-SR-B       130 non-null    float64
 10  ODI-WKTS       130 non-null    int64
 11  ODI-SR-BL      130 non-null    float64
 12  CAPTAINCY EXP  130 non-null    int64
 13  RUNS-S         130 non-null    int64
 14  HS             130 non-null    int64
 15  AVE            130 non-null    float64
 16  SR-B           130 non-null    float64
 17  SIXERS         130 non-null    int64
 18  RUNS-C         130 non-null    int64
 19  WKTS           130 non-null    int64
 20  AVE-BL         130 non-null    float64
 21  ECON           130 non-null    float64
 22  SR-BL          130 non-null    float64
 23  AUCTION YEAR   130 non-null    int64
 24  BASE PRICE     130 non-null    int64
 25  SOLD PRICE     130 non-null    int64
dtypes: float64(7), int64(15), object(4)
memory usage: 26.5+ KB

In [69]:
df.describe()

,Sl.NO.,AGE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,ODI-WKTS,ODI-SR-BL,CAPTAINCY EXP,RUNS-S,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
count,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,...,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,1.300000e+02,1.300000e+02
mean,65.500000,2.092308,2166.715385,66.530769,2508.738462,71.164385,76.076923,34.033846,0.315385,514.246154,...,111.053462,17.692308,475.523077,17.169231,23.110231,6.204462,17.382615,2009.092308,1.922308e+05,5.212231e+05
std,37.671829,0.576627,3305.646757,142.676855,3582.205625,25.898440,111.205070,26.751749,0.466466,615.226335,...,35.928907,23.828146,558.314049,21.816763,20.802057,4.941531,15.273422,1.377821,1.530973e+05,4.068074e+05
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2008.000000,2.000000e+04,2.000000e+04
25%,33.250000,2.000000,25.500000,0.000000,73.250000,65.650000,0.000000,0.000000,0.000000,39.000000,...,98.237500,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2008.000000,1.000000e+05,2.250000e+05
50%,65.500000,2.000000,542.500000,7.000000,835.000000,78.225000,18.500000,36.600000,0.000000,172.000000,...,118.510000,6.000000,297.000000,8.500000,24.785000,7.380000,19.935000,2008.000000,2.000000e+05,4.375000e+05
75%,97.750000,2.000000,3002.250000,47.500000,3523.500000,86.790000,106.000000,45.325000,1.000000,925.250000,...,129.102500,29.750000,689.250000,23.750000,35.580000,8.247500,26.212500,2011.000000,2.250000e+05,7.000000e+05
max,130.000000,3.000000,15470.000000,800.000000,18426.000000,116.660000,534.000000,150.000000,1.000000,2254.000000,...,235.490000,129.000000,1975.000000,83.000000,126.300000,38.110000,100.200000,2011.000000,1.350000e+06,1.800000e+06

In [71]:
df.max()

Sl.NO.                       130
PLAYER NAME      de Villiers, AB
AGE                            3
COUNTRY                      ZIM
TEAM                         RR+
PLAYING ROLE           W. Keeper
T-RUNS                     15470
T-WKTS                       800
ODI-RUNS-S                 18426
ODI-SR-B                  116.66
ODI-WKTS                     534
ODI-SR-BL                  150.0
CAPTAINCY EXP                  1
RUNS-S                      2254
HS                           158
AVE                        50.11
SR-B                      235.49
SIXERS                       129
RUNS-C                      1975
WKTS                          83
AVE-BL                     126.3
ECON                       38.11
SR-BL                      100.2
AUCTION YEAR                2011
BASE PRICE               1350000
SOLD PRICE               1800000
dtype: object

In [8]:
df.where(df['CAPTAINCY EXP']>0,other="neekenduku ra")

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
0,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra
1,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra
2,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra
3,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra
4,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra
126,127,Younis Khan,2,PAK,RR,Batsman,6398,7,6814,75.78,...,42.85,0,0,0,0.0,0.0,0.0,2008,225000,225000
127,128,Yuvraj Singh,2,IND,KXIP+,Batsman,1775,9,8051,87.58,...,131.88,67,569,23,24.74,7.02,21.13,2011,400000,1800000
128,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra
129,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,...,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra,neekenduku ra

In [9]:
df.loc[df['PLAYING ROLE']=='W. Keeper']

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
9,10,"Boucher, MV",2,SA,RCB+,W. Keeper,5515,1,4686,84.76,...,127.51,13,0,0,0.0,0.0,0.0,2008,200000,450000
13,14,"de Villiers, AB",2,SA,DD+,W. Keeper,5457,2,4998,93.19,...,128.53,42,0,0,0.0,0.0,0.0,2008,200000,300000
15,16,"Dhoni, MS",2,IND,CSK,W. Keeper,3509,0,6773,88.19,...,136.45,64,0,0,0.0,0.0,0.0,2008,400000,1500000
28,29,"Gilchrist, AC",3,AUS,DC+,W. Keeper,5570,0,9619,96.94,...,140.21,86,0,0,0.0,0.0,0.0,2008,300000,700000
45,46,Kamran Akmal,2,PAK,RR,W. Keeper,2648,0,2924,84.31,...,164.10,8,0,0,0.0,0.0,0.0,2008,150000,150000
47,48,"Karthik, KD",2,IND,DD+,W. Keeper,1000,0,1008,74.50,...,123.84,28,0,0,0.0,0.0,0.0,2008,200000,525000
60,61,"McCullum, BB",2,NZ,KKR+,W. Keeper,3763,0,4511,89.62,...,123.42,48,0,0,0.0,0.0,0.0,2008,175000,700000
75,76,"Ojha, NV",2,IND,RR+,W. Keeper,0,0,1,14.28,...,117.94,50,0,0,0.0,0.0,0.0,2011,100000,270000
80,81,"Patel, PA",2,IND,CSK+,W. Keeper,683,0,736,76.50,...,107.29,13,0,0,0.0,0.0,0.0,2008,150000,325000
90,91,"Saha, WP",2,IND,KKR+,W. Keeper,74,0,4,80.00,...,128.28,16,0,0,0.0,0.0,0.0,2011,100000,100000
91,92,"Sangakkara, KC",2,SL,KXIP+,W. Keeper,9382,0,10472,75.75,...,124.76,27,0,0,0.0,0.0,0.0,2008,250000,700000
109,110,"Taibu, T",2,ZIM,KKR,W. Keeper,1546,1,3393,67.58,...,119.23,0,0,0,0.0,0.0,0.0,2008,125000,125000

In [10]:
df.shape

(130, 26)

In [11]:
df.index

RangeIndex(start=0, stop=130, step=1)

In [26]:
df.columns

Index(['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE',
       'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL',
       'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C',
       'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE',
       'SOLD PRICE'],
      dtype='object')

In [28]:
df.dtypes

Sl.NO.             int64
PLAYER NAME       object
AGE                int64
COUNTRY           object
TEAM              object
PLAYING ROLE      object
T-RUNS             int64
T-WKTS             int64
ODI-RUNS-S         int64
ODI-SR-B         float64
ODI-WKTS           int64
ODI-SR-BL        float64
CAPTAINCY EXP      int64
RUNS-S             int64
HS                 int64
AVE              float64
SR-B             float64
SIXERS             int64
RUNS-C             int64
WKTS               int64
AVE-BL           float64
ECON             float64
SR-BL            float64
AUCTION YEAR       int64
BASE PRICE         int64
SOLD PRICE         int64
dtype: object

In [33]:
df[['PLAYER NAME','AVE','TEAM']].sort_values('AVE',ascending=False).head()

       PLAYER NAME    AVE  TEAM
26       Gayle, CH  50.11  KKR+
83   Pietersen, KP  42.27  RCB+
38     Hussey, MEK  39.92   CSK
111  Tendulkar, SR  37.91    MI
15       Dhoni, MS  37.13   CSK

In [37]:
df.at[15,'AVE']

37.13

In [38]:
df.iat[12,13]

337

In [41]:
df.head(14)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0.00,0,307,15,20.47,8.90,13.93,2009,50000,50000
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0.00,0,29,0,0.00,14.50,0.00,2008,50000,50000
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,121.01,5,1059,29,36.52,8.81,24.90,2008,200000,350000
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,76.32,0,1125,49,22.96,6.23,22.14,2011,100000,850000
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,120.71,28,0,0,0.00,0.00,0.00,2011,100000,800000
5,6,"Bailey, GJ",2,AUS,CSK,Batsman,0,0,172,72.26,...,95.45,0,0,0,0.00,0.00,0.00,2009,50000,50000
6,7,"Balaji, L",2,IND,CSK+,Bowler,51,27,120,78.94,...,72.22,1,1342,52,25.81,7.98,19.40,2011,100000,500000
7,8,"Bollinger, DE",2,AUS,CSK,Bowler,54,50,50,92.59,...,165.88,1,693,37,18.73,7.22,15.57,2011,200000,700000
8,9,"Botha, J",2,SA,RR,Allrounder,83,17,609,85.77,...,114.73,3,610,19,32.11,6.85,28.11,2011,200000,950000
9,10,"Boucher, MV",2,SA,RCB+,W. Keeper,5515,1,4686,84.76,...,127.51,13,0,0,0.00,0.00,0.00,2008,200000,450000
10,11,"Bravo, DJ",2,WI,MI+,Allrounder,2200,86,2004,81.39,...,127.12,38,1338,47,28.47,8.12,21.11,2011,200000,200000
11,12,"Chanderpaul, S",3,WI,RCB,Batsman,9918,9,8778,70.74,...,80.64,0,0,0,0.00,0.00,0.00,2008,200000,200000
12,13,"Chawla, PP",1,IND,KXIP,Allrounder,5,3,38,65.51,...,113.09,9,1819,73,126.30,38.11,100.20,2008,125000,400000
13,14,"de Villiers, AB",2,SA,DD+,W. Keeper,5457,2,4998,93.19,...,128.53,42,0,0,0.00,0.00,0.00,2008,200000,300000

In [4]:
df['TOTAL RUNS']=df['RUNS-S']+df['T-RUNS']+df['ODI-RUNS-S']

df[['PLAYER NAME','TEAM','TOTAL RUNS']].sort_values('TOTAL RUNS',ascending=False).head(10)

           PLAYER NAME   TEAM  TOTAL RUNS
111      Tendulkar, SR     MI       35943
86         Ponting, RT    KKR       26961
18          Dravid, RS   RCB+       25880
44          Kallis, JH    RCB       25842
42   Jayawardena, DPMD  KXIP+       22507
91      Sangakkara, KC  KXIP+       21421
41      Jayasuriya, ST     MI       21171
25         Ganguly, SC   KKR+       19924
11      Chanderpaul, S    RCB       18721
93           Sehwag, V     DD       18147

In [46]:
df.isnull()

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
126,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
127,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
128,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
129,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [47]:
df.notnull()

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
126,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
127,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
128,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
129,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [6]:
df1=df

In [7]:
df1.dropna()

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0,307,15,20.47,8.90,13.93,2009,50000,50000,0
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0,29,0,0.00,14.50,0.00,2008,50000,50000,871
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,5,1059,29,36.52,8.81,24.90,2008,200000,350000,2007
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,0,1125,49,22.96,6.23,22.14,2011,100000,850000,583
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,28,0,0,0.00,0.00,0.00,2011,100000,800000,1459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,126,"Yadav, AS",2,IND,DC,Batsman,0,0,0,0.00,...,2,0,0,0.00,0.00,0.00,2010,50000,750000,49
126,127,Younis Khan,2,PAK,RR,Batsman,6398,7,6814,75.78,...,0,0,0,0.00,0.00,0.00,2008,225000,225000,13215
127,128,Yuvraj Singh,2,IND,KXIP+,Batsman,1775,9,8051,87.58,...,67,569,23,24.74,7.02,21.13,2011,400000,1800000,11063
128,129,Zaheer Khan,2,IND,MI+,Bowler,1114,288,790,73.55,...,1,1783,65,27.43,7.75,21.26,2008,200000,450000,2003
129,130,"Zoysa, DNT",2,SL,DC,Bowler,288,64,343,95.81,...,0,99,2,49.50,9.00,33.00,2008,100000,110000,642

In [8]:
df1.fillna(12)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0,307,15,20.47,8.90,13.93,2009,50000,50000,0
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0,29,0,0.00,14.50,0.00,2008,50000,50000,871
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,5,1059,29,36.52,8.81,24.90,2008,200000,350000,2007
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,0,1125,49,22.96,6.23,22.14,2011,100000,850000,583
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,28,0,0,0.00,0.00,0.00,2011,100000,800000,1459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,126,"Yadav, AS",2,IND,DC,Batsman,0,0,0,0.00,...,2,0,0,0.00,0.00,0.00,2010,50000,750000,49
126,127,Younis Khan,2,PAK,RR,Batsman,6398,7,6814,75.78,...,0,0,0,0.00,0.00,0.00,2008,225000,225000,13215
127,128,Yuvraj Singh,2,IND,KXIP+,Batsman,1775,9,8051,87.58,...,67,569,23,24.74,7.02,21.13,2011,400000,1800000,11063
128,129,Zaheer Khan,2,IND,MI+,Bowler,1114,288,790,73.55,...,1,1783,65,27.43,7.75,21.26,2008,200000,450000,2003
129,130,"Zoysa, DNT",2,SL,DC,Bowler,288,64,343,95.81,...,0,99,2,49.50,9.00,33.00,2008,100000,110000,642

In [17]:
# total runs scpred by all players
sum(df['TOTAL RUNS'])

# maximum runs scored by a player
max(df['TOTAL RUNS'])


# median of the total runs
df['TOTAL RUNS'].median()


# mode of the total runs
df.mode()

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,1,"Abdulla, YA",2.0,IND,CSK,Bowler,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2008.0,100000.0,50000.0,583.0
1,2,Abdur Razzak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200000.0,100000.0,2084.0
2,3,"Agarkar, AB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500000.0,NaN
3,4,"Ashwin, R",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,"Badrinath, S",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,126,Younis Khan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,127,Yuvraj Singh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,128,Zaheer Khan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,129,"Zoysa, DNT",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,130,"de Villiers, AB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df.count()

Sl.NO.           130
PLAYER NAME      130
AGE              130
COUNTRY          130
TEAM             130
PLAYING ROLE     130
T-RUNS           130
T-WKTS           130
ODI-RUNS-S       130
ODI-SR-B         130
ODI-WKTS         130
ODI-SR-BL        130
CAPTAINCY EXP    130
RUNS-S           130
HS               130
AVE              130
SR-B             130
SIXERS           130
RUNS-C           130
WKTS             130
AVE-BL           130
ECON             130
SR-BL            130
AUCTION YEAR     130
BASE PRICE       130
SOLD PRICE       130
TOTAL RUNS       130
dtype: int64

In [9]:
list(df.columns)

['Sl.NO.',
 'PLAYER NAME',
 'AGE',
 'COUNTRY',
 'TEAM',
 'PLAYING ROLE',
 'T-RUNS',
 'T-WKTS',
 'ODI-RUNS-S',
 'ODI-SR-B',
 'ODI-WKTS',
 'ODI-SR-BL',
 'CAPTAINCY EXP',
 'RUNS-S',
 'HS',
 'AVE',
 'SR-B',
 'SIXERS',
 'RUNS-C',
 'WKTS',
 'AVE-BL',
 'ECON',
 'SR-BL',
 'AUCTION YEAR',
 'BASE PRICE',
 'SOLD PRICE',
 'TOTAL RUNS']

In [12]:
df.head(15).transpose()

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.0,...,0,307,15,20.47,8.9,13.93,2009,50000,50000,0
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0,29,0,0.0,14.5,0.0,2008,50000,50000,871
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,5,1059,29,36.52,8.81,24.9,2008,200000,350000,2007
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,0,1125,49,22.96,6.23,22.14,2011,100000,850000,583
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,28,0,0,0.0,0.0,0.0,2011,100000,800000,1459
5,6,"Bailey, GJ",2,AUS,CSK,Batsman,0,0,172,72.26,...,0,0,0,0.0,0.0,0.0,2009,50000,50000,235
6,7,"Balaji, L",2,IND,CSK+,Bowler,51,27,120,78.94,...,1,1342,52,25.81,7.98,19.4,2011,100000,500000,197
7,8,"Bollinger, DE",2,AUS,CSK,Bowler,54,50,50,92.59,...,1,693,37,18.73,7.22,15.57,2011,200000,700000,125
8,9,"Botha, J",2,SA,RR,Allrounder,83,17,609,85.77,...,3,610,19,32.11,6.85,28.11,2011,200000,950000,1027
9,10,"Boucher, MV",2,SA,RCB+,W. Keeper,5515,1,4686,84.76,...,13,0,0,0.0,0.0,0.0,2008,200000,450000,10595
10,11,"Bravo, DJ",2,WI,MI+,Allrounder,2200,86,2004,81.39,...,38,1338,47,28.47,8.12,21.11,2011,200000,200000,5043
11,12,"Chanderpaul, S",3,WI,RCB,Batsman,9918,9,8778,70.74,...,0,0,0,0.0,0.0,0.0,2008,200000,200000,18721
12,13,"Chawla, PP",1,IND,KXIP,Allrounder,5,3,38,65.51,...,9,1819,73,126.3,38.11,100.2,2008,125000,400000,380
13,14,"de Villiers, AB",2,SA,DD+,W. Keeper,5457,2,4998,93.19,...,42,0,0,0.0,0.0,0.0,2008,200000,300000,11757
14,15,"Dhawan, S",2,IND,MI+,Batsman,0,0,69,56.09,...,36,66,4,16.5,8.25,12.0,2011,100000,300000,1609

In [13]:
df[0:5]

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0,307,15,20.47,8.90,13.93,2009,50000,50000,0
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0,29,0,0.00,14.50,0.00,2008,50000,50000,871
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,5,1059,29,36.52,8.81,24.90,2008,200000,350000,2007
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,0,1125,49,22.96,6.23,22.14,2011,100000,850000,583
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,28,0,0,0.00,0.00,0.00,2011,100000,800000,1459

In [15]:
df[-5:]

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
125,126,"Yadav, AS",2,IND,DC,Batsman,0,0,0,0.00,...,2,0,0,0.00,0.00,0.00,2010,50000,750000,49
126,127,Younis Khan,2,PAK,RR,Batsman,6398,7,6814,75.78,...,0,0,0,0.00,0.00,0.00,2008,225000,225000,13215
127,128,Yuvraj Singh,2,IND,KXIP+,Batsman,1775,9,8051,87.58,...,67,569,23,24.74,7.02,21.13,2011,400000,1800000,11063
128,129,Zaheer Khan,2,IND,MI+,Bowler,1114,288,790,73.55,...,1,1783,65,27.43,7.75,21.26,2008,200000,450000,2003
129,130,"Zoysa, DNT",2,SL,DC,Bowler,288,64,343,95.81,...,0,99,2,49.50,9.00,33.00,2008,100000,110000,642

In [19]:
pd.set_option('display.max_columns',10)
df.head(10)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,...,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE,TOTAL RUNS
0,1,"Abdulla, YA",2,SA,KXIP,...,13.93,2009,50000,50000,0
1,2,Abdur Razzak,2,BAN,RCB,...,0.00,2008,50000,50000,871
2,3,"Agarkar, AB",2,IND,KKR,...,24.90,2008,200000,350000,2007
3,4,"Ashwin, R",1,IND,CSK,...,22.14,2011,100000,850000,583
4,5,"Badrinath, S",2,IND,CSK,...,0.00,2011,100000,800000,1459
5,6,"Bailey, GJ",2,AUS,CSK,...,0.00,2009,50000,50000,235
6,7,"Balaji, L",2,IND,CSK+,...,19.40,2011,100000,500000,197
7,8,"Bollinger, DE",2,AUS,CSK,...,15.57,2011,200000,700000,125
8,9,"Botha, J",2,SA,RR,...,28.11,2011,200000,950000,1027
9,10,"Boucher, MV",2,SA,RCB+,...,0.00,2008,200000,450000,10595

df[['PLAYER NAME','AGE']][0:5]

In [21]:
df[['PLAYER NAME','AGE']][0:5]

    PLAYER NAME  AGE
0   Abdulla, YA    2
1  Abdur Razzak    2
2   Agarkar, AB    2
3     Ashwin, R    1
4  Badrinath, S    2

In [22]:
df['PLAYER NAME'][0:10]

0      Abdulla, YA
1     Abdur Razzak
2      Agarkar, AB
3        Ashwin, R
4     Badrinath, S
5       Bailey, GJ
6        Balaji, L
7    Bollinger, DE
8         Botha, J
9      Boucher, MV
Name: PLAYER NAME, dtype: object

In [24]:
df.iloc[4:20,1:9]

,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S
4,"Badrinath, S",2,IND,CSK,Batsman,63,0,79
5,"Bailey, GJ",2,AUS,CSK,Batsman,0,0,172
6,"Balaji, L",2,IND,CSK+,Bowler,51,27,120
7,"Bollinger, DE",2,AUS,CSK,Bowler,54,50,50
8,"Botha, J",2,SA,RR,Allrounder,83,17,609
9,"Boucher, MV",2,SA,RCB+,W. Keeper,5515,1,4686
10,"Bravo, DJ",2,WI,MI+,Allrounder,2200,86,2004
11,"Chanderpaul, S",3,WI,RCB,Batsman,9918,9,8778
12,"Chawla, PP",1,IND,KXIP,Allrounder,5,3,38
13,"de Villiers, AB",2,SA,DD+,W. Keeper,5457,2,4998
14,"Dhawan, S",2,IND,MI+,Batsman,0,0,69
15,"Dhoni, MS",2,IND,CSK,W. Keeper,3509,0,6773
16,"Dilshan, TM",2,SL,DD+,Allrounder,4722,32,6455
17,"Dinda, AB",2,IND,KKR+,Bowler,0,0,18
18,"Dravid, RS",3,IND,RCB+,Batsman,13288,1,10889
19,"Duminy, J-P",2,SA,MI+,Batsman,654,11,2536

In [31]:
df.COUNTRY.value_counts()

# it counts the each value that presnet in the country column

df['PLAYING ROLE'].value_counts()

PLAYING ROLE
Bowler        44
Batsman       39
Allrounder    35
W. Keeper     12
Name: count, dtype: int64

In [36]:
df.COUNTRY.value_counts(normalize=True)*100

COUNTRY
IND    40.769231
AUS    16.923077
SA     12.307692
SL      9.230769
PAK     6.923077
NZ      5.384615
WI      4.615385
ENG     2.307692
BAN     0.769231
ZIM     0.769231
Name: proportion, dtype: float64

In [39]:
pd.crosstab(df['AGE'],df['PLAYING ROLE'])
pd.crosstab(df['PLAYER NAME'],df['AGE'])

AGE              1  2  3
PLAYER NAME
Abdulla, YA      0  1  0
Abdur Razzak     0  1  0
Agarkar, AB      0  1  0
Ashwin, R        1  0  0
Badrinath, S     0  1  0
...             .. .. ..
Younis Khan      0  1  0
Yuvraj Singh     0  1  0
Zaheer Khan      0  1  0
Zoysa, DNT       0  1  0
de Villiers, AB  0  1  0

[130 rows x 3 columns]

In [45]:
df[['PLAYER NAME','SOLD PRICE']].sort_values('SOLD PRICE')[0:10]

        PLAYER NAME  SOLD PRICE
73       Noffke, AA       20000
46      Kamran Khan       24000
0       Abdulla, YA       50000
1      Abdur Razzak       50000
118   Van der Merwe       50000
5        Bailey, GJ       50000
85   Pomersbach, LA       50000
34    Henriques, MC       50000
61     McDonald, AB       80000
78     Pankaj Singh       95000

In [44]:
df[['PLAYER NAME','SOLD PRICE']].sort_values('SOLD PRICE',ascending=False)[0:10]

       PLAYER NAME  SOLD PRICE
93       Sehwag, V     1800000
127   Yuvraj Singh     1800000
50        Kohli, V     1800000
111  Tendulkar, SR     1800000
113     Tiwary, SS     1600000
83   Pietersen, KP     1550000
23     Flintoff, A     1550000
15       Dhoni, MS     1500000
108     Symonds, A     1350000
110   Taylor, LRPL     1000000

In [46]:
df['PROFIT']=df['SOLD PRICE']-df['BASE PRICE']

In [47]:
df[["PLAYER NAME",'SOLD PRICE','BASE PRICE','PROFIT']].head(10)

     PLAYER NAME  SOLD PRICE  BASE PRICE  PROFIT
0    Abdulla, YA       50000       50000       0
1   Abdur Razzak       50000       50000       0
2    Agarkar, AB      350000      200000  150000
3      Ashwin, R      850000      100000  750000
4   Badrinath, S      800000      100000  700000
5     Bailey, GJ       50000       50000       0
6      Balaji, L      500000      100000  400000
7  Bollinger, DE      700000      200000  500000
8       Botha, J      950000      200000  750000
9    Boucher, MV      450000      200000  250000

In [49]:
df[["PLAYER NAME",'SOLD PRICE','BASE PRICE','PROFIT']].sort_values('PROFIT',ascending=False)

       PLAYER NAME  SOLD PRICE  BASE PRICE   PROFIT
50        Kohli, V     1800000      150000  1650000
113     Tiwary, SS     1600000      100000  1500000
127   Yuvraj Singh     1800000      400000  1400000
111  Tendulkar, SR     1800000      400000  1400000
93       Sehwag, V     1800000      400000  1400000
..             ...         ...         ...      ...
102      Smith, DR      100000      100000        0
73      Noffke, AA       20000       20000        0
100     Silva, LPC      100000      100000        0
74        Ntini, M      200000      200000        0
0      Abdulla, YA       50000       50000        0

[130 rows x 4 columns]

In [50]:
df.groupby('AGE')['SOLD PRICE'].mean()

AGE
1    720250.000000
2    484534.883721
3    520178.571429
Name: SOLD PRICE, dtype: float64

In [52]:
df.groupby(['AGE','PLAYING ROLE'])['SOLD PRICE'].mean()

AGE  PLAYING ROLE
1    Allrounder      5.875000e+05
     Batsman         1.110000e+06
     Bowler          5.177143e+05
2    Allrounder      4.494000e+05
     Batsman         6.547619e+05
     Bowler          3.979310e+05
     W. Keeper       4.677273e+05
3    Allrounder      7.666667e+05
     Batsman         4.576923e+05
     Bowler          4.143750e+05
     W. Keeper       7.000000e+05
Name: SOLD PRICE, dtype: float64